import Head from "next/head";
import { PostCard, Categories } from "@/components";
import { FC } from "react";
import { GetServerSideProps } from "next";
import axiosInstance from "@/config/config";
import { Category, Post } from "@/types/types";
interface HomeProps {
  posts: Post[];
  categories: Category[];
}
const Home: FC<HomeProps> = ({ posts, categories }) => {
  return (
    <div className="container mx-auto px-10 mb-8 ">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => {
            return <PostCard post={post} key={post._id} />;
          })}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <Categories categories={categories} />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const allPosts = await axiosInstance.get("post/getAllPosts");
  const allCategories = await axiosInstance.get("category/getAllCategories");
  return {
    props: {
      posts: allPosts.data.posts,
      categories: allCategories.data.categories,
    },
  };
};
